USE ZOO

GO


----------------------UPDATE ESPECIEHABITAD---------------------
CREATE PROC UPDATE_ESPECIEHABITAD
@IDESPECIE_VIEJO UNIQUEIDENTIFIER,
@IDHABITAD_VIEJO UNIQUEIDENTIFIER,
@ESPECIE UNIQUEIDENTIFIER,
@HABITAD UNIQUEIDENTIFIER,
@MENSAJE VARCHAR(100) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		----VALIDAMOS QUE NO SEAN NULOS
		IF(@ESPECIE IS NULL OR @HABITAD IS NULL OR @IDESPECIE_VIEJO IS NULL  OR @IDHABITAD_VIEJO IS NULL)
		BEGIN
			SET @MENSAJE='Los parametros no pueden ser nulos';
			RETURN;
		END

		BEGIN TRANSACTION;

		IF NOT EXISTS (SELECT 1 FROM EspecieHabitat WITH(UPDLOCK,ROWLOCK) WHERE Especie=@IDESPECIE_VIEJO AND Habitat = @IDHABITAD_VIEJO )
		BEGIN
			ROLLBACK TRANSACTION;
			SET @MENSAJE = 'La relacion a la que intenta actualizar no existe';
			RETURN;
		END

		DECLARE @EXISTSHABITAD AS BIT
		SET @EXISTSHABITAD=(SELECT EstadoHabitat FROM Habitat WITH (UPDLOCK,ROWLOCK) WHERE CodigoHabitat=@HABITAD);

		----validar que la especie existe
		IF(@EXISTSHABITAD IS NULL )
		BEGIN
			ROLLBACK TRANSACTION;
			SET @MENSAJE='la habitad no existe ';
			RETURN;
		END

		IF(@EXISTSHABITAD = 0)
		BEGIN
			ROLLBACK TRANSACTION;
			SET @MENSAJE='La habitad se encuentra inactiva';
			RETURN;
		END	
	
		DECLARE @EXISTESPECIE AS BIT 
		SET @EXISTESPECIE=(SELECT 1 FROM Especie WITH (UPDLOCK,ROWLOCK) WHERE CodigoEspecie=@ESPECIE);


		----validar que el habitad existe
		IF (@EXISTESPECIE IS NULL)
		BEGIN
			ROLLBACK TRANSACTION;
			SET @MENSAJE='La especie no existe';
		END

		IF(@EXISTESPECIE = 0)
		BEGIN
			ROLLBACK TRANSACTION;
			SET @MENSAJE='LA ESPECIE SE ENCUENTRA INACTIVA';
			RETURN
		END

		---VER SI LA RELACION EXISTE
		IF EXISTS(SELECT 1 FROM EspecieHabitat WITH (UPDLOCK,ROWLOCK) WHERE Especie=@ESPECIE AND Habitat=@HABITAD)
		BEGIN
			ROLLBACK TRANSACTION;
			SET @MENSAJE='La relacion ya existe en la base de datos';
			RETURN;
		END


		UPDATE EspecieHabitat SET
			Especie=@ESPECIE,
			Habitat=@HABITAD
		WHERE Especie=@IDESPECIE_VIEJO AND Habitat=@IDHABITAD_VIEJO;

		 -- Validar que se actualizo exactamente 1 registro
        IF @@ROWCOUNT <> 1
        BEGIN
            ROLLBACK TRANSACTION;
            SET @MENSAJE = 'Error inesperado al actualizar la tabla';
            RETURN;
        END

        COMMIT TRANSACTION;
		SET @MENSAJE='Se actualizo correctamente la relacion';
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            
        SET @MENSAJE = 'Error al actualizar la relacion: ' + ERROR_MESSAGE();
	END CATCH
END
